### ISSUE TITLE
Fix the issue of connecting external displays

### ISSUE THREAD

**Issue by Golevka2001** [PGBSean/Surface-Pro-5-OpenCore#4]
- Device: Surface Pro 5 - m3/4GB/128GB
- Graphics: Intel HD615

(I know this EFI is suitable for devices with i5 and HD620)

I don't know if it works well on HD620 devices when connecting external displays, but I failed. 

After adding the following values to `DeviceProperties-Add-PciRoot(0x0)/Pci(0x2,0x0)`, the external display is available.

Key | Type | Value
-- | -- | --
framebuffer-con1-enable | Data | 01000000
framebuffer-con1-alldata | Data | 01050A00 00080000 87010000
framebuffer-con2-enable | Data | 01000000
framebuffer-con2-alldata | Data | 03060A00 00040000 87010000

[Reference: OpenCore-Install-Guide](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/kaby-lake.html#configuration-notes)

![1703836157079](https://github.com/PGBSean/Surface-Pro-5-OpenCore/assets/101185502/6ce112d1-21e7-4ae0-8892-f430fab871f6)

**Comment by olekor** [comment]
> 03060A00 00040000 87010000

Surface Pro 5 Kaby Lake HD620 (i5) Ventura 13.6.1 was functioning perfectly until I connected an external monitor to it for the first time. When I try to turn on the tablet, the screen remains black until I plug in the mini-DP cable to connect the external monitor. I have tried changing the data with all the options in the DeviceProperties section PciRoot(0x0)/Pci(0x,0x0), but it hasn't helped. The screen doesn't switch on without a connection to an external monitor and switches off if I disconnect the external monitor. I suppose that is some problem with backlight-related functions, generally I in stuck, as tried plenty of combinations with parameters DeviceProperties and boots-arg  NVRAM, but didn't find the right variant. 
What do you use 
AAPL,ig-platform-id=?
PlatformID=?
framebuffer-stolenmem=?
boot-arg =? NVRAM
Maybe need some additional to add, besides the mentioned framebuffers for the external monitor.

**Comment by Golevka2001** [comment]
Sorry for causing it... 😭

This is my configuration for `PciRoot(0x0)/Pci(0x2,0x0)`:

<img width="1280" alt="image" src="https://github.com/PGBSean/Surface-Pro-5-OpenCore/assets/101185502/f1bec90e-803a-4478-91ea-e2fe9c4b78e6">

The `boot-args` is the same as that in this repository.

I also need to add that my device uses **m3-7y34 processor** and **HD615 graphics card**.

Finally this is my `kext` list:

<img width="1304" alt="image" src="https://github.com/PGBSean/Surface-Pro-5-OpenCore/assets/101185502/15c83dc7-8743-4199-ab5e-622265757933">

**Comment by olekor** [comment]
> Sorry for causing it... 😭
> 
> This is my configuration for `PciRoot(0x0)/Pci(0x2,0x0)`:
> 
> <img alt="image" width="1280" src="https://private-user-images.githubusercontent.com/101185502/293486884-f1bec90e-803a-4478-91ea-e2fe9c4b78e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMDY2NzYsIm5iZiI6MTcwNDAwNjM3NiwicGF0aCI6Ii8xMDExODU1MDIvMjkzNDg2ODg0LWYxYmVjOTBlLTgwM2EtNDQ3OC05MWVhLWUyZmU5YzRiNzhlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMVQwNzA2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2EzZjI5MWNiODhhMDE0YTRlMjczYjkyOGQ4MmZhZGNhZGRmMzVkNjBmZDNhZmNkZmNlNjc3MjM0MjcyOTQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ikz7UZE57q-PmDHlFbAkhNBU6Glmc3vqXUwdZPqhbrI">
> The `boot-args` is the same as that in this repository.
> 
> I also need to add that my device uses **m3-7y34 processor** and **HD615 graphics card**.
> 
> Finally this is my `kext` list:
> 
> <img alt="image" width="1304" src="https://private-user-images.githubusercontent.com/101185502/293487123-15c83dc7-8743-4199-ab5e-622265757933.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMDY2NzYsIm5iZiI6MTcwNDAwNjM3NiwicGF0aCI6Ii8xMDExODU1MDIvMjkzNDg3MTIzLTE1YzgzZGM3LTg3NDMtNDE5OS1hYjVlLTYyMjI2NTc1NzkzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMVQwNzA2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTU5YTQ0MDNhN2Y3Y2M3YzYzMWRjODdjMWFiNGNiNTUxNjkzMDg0MzhkM2Q3NTFjZDg5MGQ5NTcyYzJmM2Q1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.74_nE86NyZG6qMyU6jNYZXI2mQIAqj32bK9sPW6uKb0">

Thank you for your response, as I see
 AAPL,ig-platform-id= 0000IB59  , that is for hd 630/MacBookPro14,3 as from these source: https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md0
ID:591B000https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md0, STOLEN: 38 MB, FBMEM: 21 MB, VRAM: 1536 MB, Flags: 0x0000130B
TOTAL STOLEN: 39 MB, TOTAL CURSOR: 1 MB (1572864 bytes), MAX STOLEN: 136 MB, MAX OVERALL: 137 MB (144191488 bytes)
Model name: Intel HD Graphics KBL CRB
Camellia: CamelliaDisabled (0), Freq: 1388 Hz, FreqMax: 1388 Hz
Mobile: 1, PipeCount: 3, PortCount: 3, FBMemoryCount: 3
[0] busId: 0x00, pipe: 8, type: 0x00000002, flags: 0x00000098 - ConnectorLVDS
[2] busId: 0x04, pipe: 10, type: 0x00000800, flags: 0x00000187 - ConnectorHDMI
[3] busId: 0x06, pipe: 10, type: 0x00000400, flags: 0x00000187 - ConnectorDP
00000800 02000000 98000000
02040A00 00080000 87010000
03060A00 00040000 87010000

But your variant Grafik  HD 615:
ID: 591E0001, STOLEN: 38 MB, FBMEM: 0 bytes, VRAM: 1536 MB, Flags: 0x002B0702
TOTAL STOLEN: 39 MB, TOTAL CURSOR: 1 MB (1572864 bytes), MAX STOLEN: 115 MB, MAX OVERALL: 116 MB (122171392 bytes)
Model name: Intel HD Graphics 615
Camellia: CamelliaV2 (2), Freq: 1388 Hz, FreqMax: 1388 Hz
Mobile: 1, PipeCount: 3, PortCount: 3, FBMemoryCount: 3
[0] busId: 0x00, pipe: 8, type: 0x00000002, flags: 0x00000098 - ConnectorLVDS
[1] busId: 0x05, pipe: 9, type: 0x00000400, flags: 0x00000181 - ConnectorDP
[2] busId: 0x04, pipe: 10, type: 0x00000400, flags: 0x00000181 - ConnectorDP
00000800 02000000 98000000
01050900 00040000 81010000
02040A00 00040000 81010000

 so, based on these recommendations, all these parameters are like a roulette, maybe you will guess, but maybe it won’t work, this probably happened in my case. I'll probably try to reinstall the OS. This is all very strange for me, since six months ago I installed a Hackintosh on a Surface Book 2 with a similar hardware composition using the same config. playlist without any problems.
Good luck and Happy New Year!

**Comment by Golevka2001** [comment]
Thank you very much for resolving my doubts.

After setting the `AAPL,ig-platform-id` value to `00001E59` (the correct device ID), the patches I mentioned at the beginning are no longer needed, the external display is back to normal now.

I was indeed trying params blindly, I didn't know why it worked properly or why it didn't work. 😿

Thank you for your reply, which has shown me how to find detailed information about my graphics card.

Wishing you a happy new year!

**Comment by olekor** [comment]
> Thank you very much for resolving my doubts.
> 
> After setting the `AAPL,ig-platform-id` value to `00001E59` (the correct device ID), the patches I mentioned at the beginning are no longer needed, the external display is back to normal now.
> 
> I was indeed trying params blindly, I didn't know why it worked properly or why it didn't work. 😿
> 
> Thank you for your reply, which has shown me how to find detailed information about my graphics card.
> 
> Wishing you a happy new year!
I am glad that at least you succeeded, but unfortunately, I have no progress, although I found similar problems that were three years ago and there were no results to solve

**Comment by olekor** [comment]
I am glad that at least you succeeded, but unfortunately, I have no progress, although I found similar problems that were three years ago and there were no results to solve
